services:
  backend:
    build:  
      context: ./backend
      dockerfile: Dockerfile.prod

    env_file:
      - ./backend/.env.prod

    depends_on:
      - db

  frontend:
    build: ./frontend/my-project
    depends_on:
      - backend

  db:
    image: postgres:15
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data

  

volumes:
  pgdata:

