

services:
  backend:
    build: ./backend
    restart: always
    env_file:
      - backend/.env.prod
    command: ["gunicorn", "--bind", "0.0.0.0:8000", "my_project.wsgi:application"]
    volumes:
      - ./backend/staticfiles:/app/staticfiles

  frontend:
    build: ./frontend/my-project
    restart: always
    command: ["npm", "run", "build"]

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.prod.conf:/etc/nginx/conf.d/default.conf:ro
      - ./backend/staticfiles:/app/staticfiles
      - ./frontend/my-project/dist:/app/frontend/dist
    depends_on:
      - backend

volumes:
  pgdata:
