services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/staticfiles:/app/staticfiles  # Даем backend доступ к папке статики
    env_file:
      - ./backend/.env  # Загружаем переменные окружения
    depends_on:
      - db
    

  frontend:
    build: ./frontend/my-project
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/my-project:/app
    env_file:
      - ./frontend/my-project/.env
    depends_on:
      - backend
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./backend/staticfiles:/app/staticfiles  # Используем ту же папку статики, что и в backend
    depends_on:
      - backend

volumes:
  pgdata:
