

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod  # Указываем отдельный Dockerfile для продакшена
    env_file:
      - ./backend/.env.prod  # Используем продакшен-окружение
    ports:
      - "8000:8000"
    volumes:
      - ./backend/staticfiles:/app/staticfiles  # Для работы статики
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend/my-project
      dockerfile: Dockerfile.prod
    env_file:
      - ./frontend/my-project/.env.prod  # Продакшен-окружение
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/my-project/dist:/app/frontend/dist
    environment:
      DJANGO_ENV: "prod"
      
    depends_on:
      - backend

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.prod.conf:/etc/nginx/conf.d/default.conf:ro
      - ./backend/staticfiles:/app/staticfiles
      - ./frontend/my-project/dist:/app/frontend/dist
    depends_on:
      - backend
      - frontend

volumes:
  pgdata:
