services:
  backend:
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/staticfiles:/app/staticfiles
    env_file:
      - ./backend/.env.dev
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]

  frontend:
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/my-project:/app
    env_file:
       - ./frontend/my-project/.env.dev 
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]

  db:
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro
      - ./backend/staticfiles:/app/staticfiles
      - ./frontend/my-project/dist:/app/frontend/dist
    depends_on:
      - backend
      - frontend
